package eu.caiq.imagesorter.sync.data.db

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import eu.caiq.imagesorter.sync.data.db.dao.FailureDao
import eu.caiq.imagesorter.sync.data.db.dao.MediaDao
import eu.caiq.imagesorter.sync.data.db.dao.PendingUploadDao
import eu.caiq.imagesorter.sync.data.db.dao.SyncedCacheDao
import eu.caiq.imagesorter.sync.data.db.entity.FailureEntity
import eu.caiq.imagesorter.sync.data.db.entity.MediaEntity
import eu.caiq.imagesorter.sync.data.db.entity.MediaRemoteKey
import eu.caiq.imagesorter.sync.data.db.entity.PendingUploadEntity
import eu.caiq.imagesorter.sync.data.db.entity.SyncedCacheEntity

/**
 * Local Room cache. This database is a rebuildable cache of server truth plus the
 * local upload queue and failure log — never the source of truth. It can be
 * dropped and regenerated by re-running discovery + reconcile.
 */
@Database(
    entities = [
        SyncedCacheEntity::class,
        PendingUploadEntity::class,
        FailureEntity::class,
        MediaEntity::class,
        MediaRemoteKey::class,
    ],
    version = 5,
    exportSchema = false,
)
abstract class AppDatabase : RoomDatabase() {

    abstract fun syncedCacheDao(): SyncedCacheDao
    abstract fun pendingUploadDao(): PendingUploadDao
    abstract fun failureDao(): FailureDao
    abstract fun mediaDao(): MediaDao

    companion object {
        fun build(context: Context): AppDatabase =
            Room.databaseBuilder(
                context.applicationContext,
                AppDatabase::class.java,
                "image_sorter_sync.db",
            )
                // Cache is rebuildable, so a destructive migration is acceptable.
                .fallbackToDestructiveMigration()
                .build()
    }
}
